print("Default arrow")
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
print("Using \\n:")
print("    *\n   * *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *****")
print("Twice big arrow")
print("     * ")
print("    * * ")
print("   *   * ")
print("  *     * ")
print(" *       * ")
print("*         * ")
print("****   ****")
print("   *   * ")
print("   *   * ")
print("   *   * ")
print("   *   * ")
print("Two arrows")
print("    *         *")
print("   * *       * * ")
print("  *   *     *   * ")
print(" *     *   *     * ")
print("***   *** ***   ***")
print("  *   *     *   *")
print("  *   *     *   *")
print("  *****     *****")
print("Two arrows Version 2")
print("    *     "*2)
print("   * *    "*2)
print("  *   *   "*2)
print(" *     *  "*2)
print("***   *** "*2)
print("  *   *   "*2)
print("  *   *   "*2)
print("  *****   "*2)